### ISSUE TITLE
Mod_productos: mejorar busqueda en productos

### ISSUE THREAD

**Issue by olallis** [TPVFox/TPVFox#10]
Poder buscar por proveedor y asi ver que productos tenemos de el. 
Se tendra que tener en cuenta tanto el idProveedor como la referencia antigua del proveedor.. para mejorar lo mostrado

SELECT a.idArticulo,a.articulo_name as articulo_name
,a.idProveedor,atienda.crefTienda,a.ultimoCoste,a.beneficio,a.iva,p.pvpSiva,p.pvpCiva,a.estado
             FROM `articulos` AS a 
		LEFT JOIN `articulosPrecios` AS p
		ON p.`idArticulo` = a.`idArticulo`
                LEFT JOIN `articulosTiendas` AS atienda 
                ON atienda.`idArticulo` = a.`idArticulo`
                WHERE a.`idProveedor` = 11 OR atienda.`crefTienda` LIKE '103%'

**Comment by Ricardolau** [comment]
Pienso que eso deberían ser filtros no en busqueda.
O quiere que busque en las referencias de los proveedores... 
No se aun no lo veo muy claro., el uso .. es decir en que momento vas a buscar la referencia del proveedor en el listado productos... cual es uso.. ?
Lo de filtrar por proveedor me parece interesante.. pero lo de buscar... no se..

**Comment by Ricardolau** [comment]
Solucionado con los filtros proveedores y familias... :-)
