### ISSUE TITLE
Error al utilizar check seleccionar todos en Productos

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#111]
Si utilizamos el check seleccionar todos en Productos cuando solo nos muestra menos cuarenta, genera uno mas en la seleccion.
Ver video explicativo del error
[https://youtu.be/EwEjItGq81w](https://youtu.be/EwEjItGq81w)

**Comment by nataliaglez** [comment]
Resuelto, el error era que seleccionaba un campo en blanco
