### ISSUE TITLE
Recuerda que SuNumero es un varchar.. :-)

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#13]
https://github.com/TPVFox/TPVFox/blob/be43b0b6769baa27e646c0708992f556cd378905/modulos/mod_compras/albaran.php#L176
No sería: 
`cabecera['suNumero']='<?php echo $suNumero; ?>';`
@nataliaglez

**Comment by nataliaglez** [comment]
commit 30e3fe29dd246e59cc56bf5da3082e58127a9149
Modificado en factura y albarán
