### ISSUE TITLE
Error al añadir un producto nuevo

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#137]
A la hora de añadir un producto nuevo:
Si cubres todo, ya que te lo permite.
Codbarras
Referencia Proveedor 
Familia ( ES AQUI EL PROBLEMA) ya que reinicia y se pierde los datos.

No indica error y NO nos carga nuevamente los datos, te queda como si acabaras abrir ficha de uno NUEVO 
Pienso que realmente lo hace cuando añadimos la familia, ahi te queda en blanco.
El error que guarda en log el servidor es:
 [php7:notice] [pid 31370] PHP Notice:  Undefined index: productos_seleccionados in /modulos/mod_producto/tareas.php on line 48, referer: /tpvfox/modulos/mod_producto/producto.php
[php7:warn] PHP Warning:  Invalid argument supplied for foreach() in tpvfox/modulos/mod_producto/tareas.php on line 51, referer: tpvfox/modulos/mod_producto/producto.php

**Comment by nataliaglez** [comment]
EL error en familias esta resuelto.
Queda pendiente el error en proveedores. Cuando es un producto nuevo no guarda el proveedor

**Comment by Ricardolau** [comment]
Lo cierro, aunque queda pendiente que añada la referencia de proveedor ya que esa no la hace.
