### ISSUE TITLE
Buscador clientes tickets

### ISSUE THREAD

**Issue by nataliaglez** [TPVFox/TPVFox#139]
En el buscador de clientes tickets hay que mejorar algunas cosas:
- Que se pueda buscar por número de teléfono
- En la busqueda de cliente que no muestre los que están de baja

**Comment by nataliaglez** [comment]
Ya buscar tanto por el campo teléfono como por el campo movil

**Comment by Ricardolau** [comment]
Esta resuelto

**Comment by Ricardolau** [comment]
Solo reabro para comentar lógica.
Al abrir un ticket si seleccionamos el cliente, este lo muestra en el ticket, pero si no tiene productos no esta grabado, ya que no tiene sentido crear un ticket temporal con el nombre de un cliente y no tenga producto.
**Se puede interpretar como un ERROR cuando pulsamos F5 sin haber metido ningún producto, se borra el cliente.**
 
 Realmente es un defecto, no un error.
