### ISSUE TITLE
funcion abrirModal repetida, reducir codigo

### ISSUE THREAD

**Issue by olallis** [TPVFox/TPVFox#17]
Funcion abrirModal js esta repetida en :  
Diferencias los focus.. al abrir el modal. 
mod_compras   --> focus en cajaBusquedaproveedor  (pendiente de poner, y asi con tabulador nos movemos por modal)
mod_ventas     --> focus cajaBusquedacliente     (NO funciona correctamente.. tiene foco pero no se mueve, se pierde.. no se.. )
mod_cierres    --> focus ¿? no se, creo que sobra o no..   
mod_tpv         -->  focus en cajaBusquedacliente,     (funciona correctamente)
                                          cajaBusqueda,  
                                         entrega
*hablo de moverme con teclado, bien tabulador o flechas.. y evitar raton. jeje

**Comment by nataliaglez** [comment]
commit 22d366d0de67a37fbf73a4379a87778043269609
commit d285ddb9a9189a81f8d568f8b307d569740c6c72

Comits de modificaciones de compras

**Comment by nataliaglez** [comment]
commit 1f763277e72ecb50581c1bf22a44e3a0f78752e3

Comist  en modificaciones de ventas

**Comment by nataliaglez** [comment]
commit fa16ae228b546418de4268c2c6be800889b6fdce

Commit de incidencias

**Comment by Ricardolau** [comment]
Cerrado ya que esta realizado.. :-)
