### ISSUE TITLE
Mod_tpv: Poner peso de la fruta en los tickets

### ISSUE THREAD

**Issue by nataliaglez** [TPVFox/TPVFox#21]

**Comment by Ricardolau** [comment]
Al imprimir una copia de un ticket pone los 3 digitos, al imprimir el ticket al cobrar pone 1 digito .
Lo correcto debería ser:
Cuando es de peso, se imprime los tres digitos, pero cuando no es por peso, solo se imprime un ticket.

**Comment by Ricardolau** [comment]
[img-425091833.pdf](https://github.com/TPVFox/TPVFox/files/3116144/img-425091833.pdf)

**Comment by Ricardolau** [comment]
![impresion_tickets](https://user-images.githubusercontent.com/1144127/56724807-fd37a000-674b-11e9-94da-9c68f0335270.png)
