### ISSUE TITLE
Albaran de cliente duplicado

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#26]
Albaran temporal 20 , albaran 53
Al cambiar un dato, intentar guardar sin pulsar intro, genera el error, tengo pantallazo creado...
Y luego al pulsar intro, generar un nuevo albaran.... 
@nataliaglez

**Comment by nataliaglez** [comment]
commit f9618fdc1ffecfe09d9d91b09497b60e63c59bbd

**Comment by nataliaglez** [comment]
No te olvides de intentar reproducir el fallo para poder cerrarlo
