### ISSUE TITLE
Mod_ventas

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#27]
https://github.com/TPVFox/TPVFox/blob/005a2fea24f1db61e914d46242bd38d354a74d58/modulos/mod_venta/tareas.php#L453-L464
@nataliaglez 
No lo entiendo, pretendes con esto?
Recores un array de productos
Si producto es array, pones bandera en 1, pero sigue haciendo foreach...
Y luego haces lo mismo tanto sea o no un array...

No lo comprendo, me parece que sobra todo...

**Comment by nataliaglez** [comment]
La dejo comentada en el comit:
commit d1d996b850dfe5cd028d57cf1bcb251a4d6816f4

**Comment by nataliaglez** [comment]
Modificada para no tener la bandera
commit 758108f4d75584117b20ed615b57b79098dfbae5

**Comment by Ricardolau** [comment]
Doy por cerrado.. :-)
commit 360b6fa863ae7be094110b95303c5ac57ca0ad01
