### ISSUE TITLE
Mod_compras: Pedidos botton eliminar

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#29]
Botton de poder eliminar el pedido.

En todos debería informar al pulsar en el, diciendo algo asi:
Va eliminar el pedido, el  albaran o la factura  temporal que tienes generado o se genero al modificarlos...

Ya veo que si informas que no se puede cancelar cuando esta guardado... :-)

**Comment by nataliaglez** [comment]
Botón cancelar pedido temporal en compras

commit 95c12887413f8b9b1dbdced8110c6477322f52b9

**Comment by nataliaglez** [comment]
Muestra alert con comprobación de cancelación y si responde errores al cancelar, En compras
commit 16f12b1a3a49d17037f0fa8b766fccd9b0f53674

**Comment by nataliaglez** [comment]
Muestra alerts con comprobaciones de cancelación en Ventas
commit 326c7a5b2320f7c68948fae765f3b387b558c0d2
