### ISSUE TITLE
Error de envio de mas de 1000 variables. 

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#3]
PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer: http://localhost/superoliva/tpvfox/modulos/mod_tpv/tpv.php?tAbierto=40
Al grabar el ticket, albaran, factura con muchas lineas ( 100) genera una adevertencia y error en php.

**Comment by Ricardolau** [comment]
Pienso que esta resuelto con los commits:
85d52d8c00666c41c43646211cec588b9d400fdc
0a586a3902e509a12ac9a7883ec7a07d45d1d773
e5c1a27f35024380fc30d7bd7194f6f0e7510eec

La solucion fue:
Enviar por JSON ...

**Comment by Ricardolau** [comment]
Esta pendiente en solucionar en pedidos , albaranes y facturas de clientes, cuando este lo cerramos @nataliaglez

**Comment by Ricardolau** [comment]
Esta pendiente en solucionar en pedidos , albaranes y facturas de clientes, cuando este lo cerramos @nataliaglez

En tpv ya lo arregle. no se en que commit... :-)

**Comment by nataliaglez** [comment]
commit cef3de0757aef683c472c0b259963251d7f664e3 
Ya están en ventas
Lo puedes dar por cerrado

**Comment by Ricardolau** [comment]
ok

**Comment by Ricardolau** [comment]
La solucion para el error de  "Input variables exceeded 1000" hay que entender cuando enviamos un array por post , por Javascript (AJAX) este genera una variable por cada index del array, por ello se debe convertir ese array ( matriz) en string con JSON.stringify(matriz)
