### ISSUE TITLE
Mod_compras: fecha

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#30]
La fecha en los pedidos, albaranes, facturas  debe ponerse en formato dd/mm/aaaa ya que normalmente lo que se cambia unicamente es el dia, haría que fuera mas sencillo cambiarla.

**Comment by nataliaglez** [comment]
Queda cambiado en todos , el comit siguiente es el del bug de al modificar un albaán la fecha estaba mal
commit e1926a357c7cabf1c68b4798b6b0f91345d3aecf
