### ISSUE TITLE
Mod_compras: Fecha de actualizacion 

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#31]
La fecha actualizacion se va cambiar date time, por lo que debe comprobar y actualizar es date time.
Hay que probar si funciona igualmente aunque el campo este ahora como date.
De momento en BD de produccion va estar como date
Y en las BD desarrollo debe estar como datetime.
Por eso debemos probar si funciona de las dos formas.

**Comment by nataliaglez** [comment]
Dejando preparado el formato date('Y-m-d H:i:s'), a la hora de modificar la base de datos 

![imagen](https://user-images.githubusercontent.com/35041376/39439967-ab8431fa-4ca9-11e8-8355-cbd38ced0bcb.png)

**Comment by Ricardolau** [comment]
Si se puede utilizar NOW porque no utilizarlo, asi creo que funcionaria tanto una u otra fecha..

**Comment by Ricardolau** [comment]
Creo que esta resuelto..
