### ISSUE TITLE
Mod_incidencias:  No entiendo el comentario

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#33]
https://github.com/TPVFox/TPVFox/blob/d0f365fd5b2f1201a0b1c10364eb177b32ea0dd5/modulos/mod_incidencias/ClaseIncidencia.php#L29

**Comment by nataliaglez** [comment]
Que busca todas las etiquetas según el paginado del listado, según la página que se pulso

**Comment by nataliaglez** [comment]
Estaba mal el comentario 
commit e8d4dcd4c14ae32872d2e581a446a8344e821421
