### ISSUE TITLE
Mod_ventas: Facturacion permitir añadir albaranes si esta en 0

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#36]
Cuando eliminamos todos los albaranes de una factura para poder modificarlos, luego esa factura se queda guarda en 0
Pero al modificar ya no permite añadir albaranes.

**Comment by nataliaglez** [comment]
En compras:
commit a9d694ea54fcf1be0926dcc0adc18d0df00a002b
En ventas:
commit de5fb20f8e656e48fb584c241efabbb50145a016
