### ISSUE TITLE
mod_producto: Recalculo productos desde compras

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#38]
Creo que el estado siempre pone A mano o pone Recomendado, tampoco pone el usuario que lo hizo.

**Comment by nataliaglez** [comment]
Hay tres estados:
- Revisado : cuanod estamos en recalculoPrecio y guardamos el precio que viene del albaran
- A mano: que el precio se modificó a mano
- Recomendado: que se dejó el precio recomendado
