### ISSUE TITLE
Errores mostrados al meter un albaran

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#4]
`
INSERT INTO albproltemporales ( idUsuario , idTienda , estadoAlbPro , fechaInicio, idProveedor,  Productos, Pedidos , Su_numero) 
VALUES (5 , 1 , "Abierto" , "2018-04-12", 63 , '[{"ccodbar":null,"cdetalle":"BANDEJA  C\/TAPA PLASTICO 1L.","cref":"086-999","crefProveedor":null,"estado":"Activo","idArticulo":"8338","iva":"21.00","ncant":1,"nfila":1,"nunidades":1,"ultimoCoste":"0.2500","importe":"0.25"}]' , '""', )
`

- El Su_numero o pedido esta mal..

**Comment by Ricardolau** [comment]
[https://github.com/TPVFox/TPVFox/blob/1ac1e834839d0b5b5778cb99677caf5b6e8d4f1f/modulos/mod_compras/clases/albaranesCompras.php#L59](url)
Esta linea no de esta bien @nataliaglez 
Esta que tal:
		$sql='UPDATE albproltemporales SET idUsuario ='.$idUsuario.' , idTienda='.$idTienda.' , estadoAlbPro="'.$estadoPedido.'" , fechaInicio="'.$fecha.'"  ,Productos='."'".$UnicoCampoProductos."'".', Pedidos='."'".$UnicoCampoPedidos."'".' , Su_numero="'.$suNumero.'" WHERE id='.$idAlbaranTemporal;

**Comment by Ricardolau** [comment]
Lo mismo , creo puedes sustituir en linea 79 ...  por este... 
		`$sql='INSERT INTO albproltemporales ( idUsuario , idTienda , estadoAlbPro , fechaInicio, idProveedor,  Productos, Pedidos , Su_numero) VALUES ('.$idUsuario.' , '.$idTienda.' , "'.$estadoPedido.'" , "'.$fecha.'", '.$idProveedor.' ,'."'".$UnicoCampoProductos."'".' ,'."'".$UnicoCampoPedidos."'".', "'.$suNumero.'")';
`

**Comment by nataliaglez** [comment]
commit 5106f8bd83ba9d03a1e0ad1bfd59448a6ca798bb

**Comment by nataliaglez** [comment]
EL commit anterior es de compras
Este es ventas como no tiene su_numero solo cambie la comprobación de array
commit 5f0ae43a45f5ecd003263719f3d0b17d8ab04ba7

**Comment by Ricardolau** [comment]
Esperamos unos días antes de cerrar , para ver si con eso ya se soluciona.... :-)
