### ISSUE TITLE
Mod_compras y Mod_ventas: añadir num factura

### ISSUE THREAD

**Issue by nataliaglez** [TPVFox/TPVFox#46]
En los albaranes tanto de compras como de ventas mostrar el número de la factura una vez que están facturados.

**Comment by nataliaglez** [comment]
commit de albaranes compras: commit b4f1d4c463eb0fec00f1ecec752c2fb8d57bdfc5
Lo realicé con la función en albaranes de NumfacturaDeAlbaran(NumAlbaran)
public function NumfacturaDeAlbaran($numAlbaran){	
		$db=$this->db;
		$tabla='albprofac';
		$where='`numAlbaran`='.$numAlbaran;
		$albaran = parent::SelectUnResult($tabla, $where);
		return $albaran;
	}
en albaran.php compruebo que el estado de la factura es facturado y si es así cargo la función anterior.
Si el estado es facturado muestra por pantalla el número de factura

**Comment by nataliaglez** [comment]
Commit en albaranes de ventas:
commit 6ef4f9f122faccf8248e796b95d51895c4ab686a
Utilizo una función igual que la del comentario anterior y la misma manera de ponerlo en albaran.php
En un futuro esa función podría ser común para los dos

**Comment by Ricardolau** [comment]
@nataliaglez  en compras el numero no pone el del albaran , no el de la factura.
![imagen](https://user-images.githubusercontent.com/1144127/42415458-755ec14a-824f-11e8-923f-9ff252ee28ed.png)

**Comment by nataliaglez** [comment]
commit 01bb84bebec438cc8a9007d68350e8c6acc98514
