### ISSUE TITLE
Mod_productos: estados Historico costes

### ISSUE THREAD

**Issue by nataliaglez** [TPVFox/TPVFox#53]
En la tabla de historico_costes, un registro puede tener 3 estados:
- Pendiente: El registro está pendiente de revisión, esto quiere decir que ha tenido un cambio de precio en un albarán de compras pero no se ha ejecutado el cambio de precio de venta.
- Recomendado: Se ha modificado el precio de venta y se ha dejado el recomendado por la aplicación
- A mano:  Se ha modificado el precio de venta pero este precio lo ha modificado el usuario.
- Sin cambios: Es el producto que se dio a eliminar desde el recalculo y no se registra modificación de precio
- Revisado: Los registros que vienen de albaranes cuando se les cambia el precio pasan de pendiente a revisado.
- Sin revisar: Son los registros que han sido modificados de precio en fechas posteriores, cuando se guarda en recalculo los productos con este estado no se pueden guardar .

**Comment by Ricardolau** [comment]
Lo cierro ya creo una entrada en [ayuda.svigo.es](http://ayuda.svigo.es/index.php/otros/portafolios/83-tpvfox-gestion-de-empresa/202-tabla-de-estados) para poder planificar como crear,aplicar una tabla de estados.
