### ISSUE TITLE
Lineas comentadas innecesarias.

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#6]
https://github.com/TPVFox/TPVFox/blob/1ac1e834839d0b5b5778cb99677caf5b6e8d4f1f/modulos/mod_compras/albaran.php#L33;L76
#5  LImpiar esta lineas comentadas ... @nataliaglez

**Comment by nataliaglez** [comment]
commit 1a4687b092d14e178f96c42d8c75254ada8aca4d
