### ISSUE TITLE
Error en permiso en cada usuario

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#61]
Debe mostrar que permisos tiene al entrar un usuario en su ficha, no permitir cambiarlo  sino es administrador pero mostralos si.
![imagen](https://user-images.githubusercontent.com/1144127/43288548-7ebea3d0-9128-11e8-8afd-8bb4f3c880c2.png)

**Comment by nataliaglez** [comment]
![captura de pantalla de 2018-08-13 16-25-27](https://user-images.githubusercontent.com/35041376/44038079-37465718-9f16-11e8-835a-72c0fa3d0ee5.png)
Está resuelto

**Comment by Ricardolau** [comment]
Aunque los muestra, la esta disable, no los envia , por ello cuando cambia las contraseña por ejemplo, el usuario pierde los permisos.
Por lo que vamos optar por los permisos que tenga no le ponemos disabled , por lo que el usuario podrá deactivarlos , cosa que creo que no haría. jejeje
Asi de esta forma al hacer un cambio, pienso que no perdera los permisos.
No es la solución ideal, pero es una. :-)
