### ISSUE TITLE
Resumen de compras o ventas, en cliente o proveedores orden producto.

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#62]
Poner ordenado los productos.

**Comment by nataliaglez** [comment]
Resumen Clientes:
commit cae0af300abeaec5700195ac96cef3e2852a6a10
 Resumen Proveedor:
commit 09bfb7bae178ee8b47e5df5fc5d4fb234f9da0b4
 En los dos he utilizado la función array_multisort (Ordena varios arrays, o arrays multidimensionales)
