### ISSUE TITLE
Resumen Albaranes Compras por fechas error

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#63]
Error en resumen por fechas de compras.
![imagen](https://user-images.githubusercontent.com/1144127/43349645-8ae542f2-9201-11e8-8258-ce63cea527d8.png)

**Comment by nataliaglez** [comment]
commit bd9f663e410399c0868457b5f6e6ee45bb1d9d20

Ahora muestra un error cuando la consulta de fechas no obtiene ids
