### ISSUE TITLE
Errores de eliminar Productos

### ISSUE THREAD

**Issue by nataliaglez** [TPVFox/TPVFox#66]
Nombre:*** BOMBILLA VELA CLARA 40W E-14
id=2607
idTicket: 22696
Error: no aparece en mayor 

Nombre: *** ENSALADA JUDIAS C/ESPINACAS 240grs.
id=2155
idPedido proveedor: 188

Nombre: LUJO ORIENTAL (FARO VIGO)
id=3186
id ticket:39370
Error: no aparece en mayor 

Nombre: MANTA MON SAC(FARO VIGO)
id:3297
id ticket: 23815
Error: no aparece en mayor 

Nombre: MANTA MON SAC(FARO VIGO)
id:5955
id ticket:17358
Error: no aparece en mayor

**Comment by Ricardolau** [comment]
El motivo es porque puede aparecer en pedidos de proveedor o clientes, tambien puede ser porque puede aparecer en tickets pero el estado de la linea esta marcada como borrada..
De momento esto no tenemos solucion...
