### ISSUE TITLE
Al descontar stock en la web desde ticket cerrado 

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#69]
No pone estado en la tabla `importar_virtuemart_tickets` y tampoco indica cuantos registros cambio, aunque esto ultimo no hace falta, solo que indique que hay error o correcto el estado.
![imagen](https://user-images.githubusercontent.com/1144127/46503808-48c84200-c82c-11e8-9c9e-9acede216ef5.png)

**Comment by nataliaglez** [comment]
commit 94134e29e823a8a1f5b5e0b5a8f565d3daf54263
