### ISSUE TITLE
Es un array no un string

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#7]
https://github.com/TPVFox/TPVFox/blob/1ac1e834839d0b5b5778cb99677caf5b6e8d4f1f/modulos/mod_compras/tareas.php#L294
#4 @nataliaglez  es un array no un string , por eso falla..

**Comment by nataliaglez** [comment]
En ventas:
commit 5f0ae43a45f5ecd003263719f3d0b17d8ab04ba7
En compras:
commit d1a77e215b7b6eccc111e53e08ce89b318826cca

**Comment by Ricardolau** [comment]
Solucionado...
