### ISSUE TITLE
Error al introducir importe al cobrar

### ISSUE THREAD

**Issue by Ricardolau** [TPVFox/TPVFox#97]
Al introducir el importe cobrado, tenemos que limitar importe , ya que por error puede pasar un código de barras y esto provoca un error.
VALIDAR CAMPO CON:
- No negativos
- No mayor de 9999€

**Comment by nataliaglez** [comment]
EL error se muestra cuando la cantidad de la línea es mas de 1000.
Ej: Suele pasar cuando en el cantidad se pasa un código de barras

**Comment by Ricardolau** [comment]
Rotura en funcion grabarTicketCobrado()-> Consulta:INSERT INTO `ticketslinea`(`idticketst`,`Numticket`, `idArticulo`, `cref`, `ccodbar`, `cdetalle`, `ncant`, `nunidades`, `precioCiva`, `iva`,nfila,estadoLinea) VALUES (108112,45381,8265,"103-40743","8480013250227","vinagre spar sidra manzana 1l",7611612221023,7611612221023,0.79,10.00,1,"Eliminado"),(108112,45381,7040,"000-37078","7611612221023","REFRESCO LATA ENERGY DRINK POWERKING 250ml",1,1,0.45,21.00,2,"Activo"),(108112,45381,3053,"1741","7611612502023","CERVEZA EMDBRAU LATA",1,1,0.35,21.00,3,"Activo"),(108112,45381,3053,"1741","7611612502023","CERVEZA EMDBRAU LATA",1,1,0.35,21.00,4,"Activo")

[{"errno":1264,"sqlstate":"22003","error":"Out of range value for column 'ncant' at row 1"}]

El error sigue...

**Comment by Ricardolau** [comment]
Esta corregido.
